/** City and state notes for the Hibachi King blog. Facts stay on the shared menu. Local copy is the place. */

const IMG = [
  "/media/gallery/party-1.webp",
  "/media/gallery/party-2.webp",
  "/media/gallery/party-3.webp",
  "/media/gallery/party-4.webp",
  "/media/gallery/party-5.webp",
  "/media/gallery/party-6.webp",
];

function cityPost(note) {
  return {
    region: "city",
    image: note.image,
    kicker: note.kicker,
    slug: `outdoor-hibachi-in-${note.id}`,
    h1: `Outdoor hibachi in ${note.name}`,
    title: `Outdoor Hibachi in ${note.name}, ${note.abbr} | Hibachi King`,
    description: note.description,
    dek: note.dek,
    landing: `/${note.landing}/`,
    landingLabel: `${note.name} page`,
    book: `/booking/${note.booking}/`,
    bookLabel: `Book ${note.name}`,
    related: note.related,
    links: note.links,
    blocks: note.blocks,
  };
}

function statePost(note) {
  return {
    region: "state",
    image: note.image,
    kicker: note.kicker,
    slug: `outdoor-hibachi-across-${note.slug}`,
    h1: `Outdoor hibachi across ${note.name}`,
    title: `Outdoor Hibachi across ${note.name} | Hibachi King`,
    description: note.description,
    dek: note.dek,
    landing: `/${note.slug}/`,
    landingLabel: `${note.name} cities`,
    book: "/book-online/",
    bookLabel: "Choose a city",
    related: note.related,
    links: note.links,
    blocks: note.blocks,
  };
}

export function regionPosts() {
  const cities = [
    cityPost({
      id: "austin",
      name: "Austin",
      abbr: "TX",
      landing: "austin-hibachi-at-home",
      booking: "austin-tx",
      image: IMG[0],
      kicker: "Austin",
      description: "Outdoor hibachi in Austin for South Congress, the Domain, Round Rock, Cedar Park, Westlake, and Lakeway. $50 per person, $500 minimum.",
      dek: "A home market, from central patios out to Round Rock, Cedar Park, and the lake.",
      related: ["outdoor-hibachi-across-texas", "outdoor-hibachi-in-dallas", "outdoor-hibachi-in-houston", "outdoor-hibachi-cost"],
      links: [
        { href: "/blog/outdoor-hibachi-across-texas/", label: "Texas overview" },
        { href: "/blog/outdoor-hibachi-in-dallas/", label: "Dallas" },
        { href: "/blog/outdoor-hibachi-in-fort-worth/", label: "Fort Worth" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Austin is one of Hibachi King's home markets, so the dates cover houses inside the city and yards north and west of it. Downtown and South Congress parties are often a patio or a small yard. Round Rock, Cedar Park, Westlake, Lakeway, and Bee Cave usually have more lawn, which changes where the grill can sit, not the menu."] },
        { h2: "Where the grill goes", p: ["The chef cooks outside. A Domain terrace, a South Congress patio, and a Lakeway backyard all qualify when there is a safe spot for the grill. Guests can eat at the grill or at a table inside. The host still sets tables, chairs, plates, and utensils. The chef brings the grill, the food, and the show."] },
        { h2: "The parties people book", p: ["Austin dates are often birthdays, graduations, and bachelor or bachelorette weekends, plus a Friday dinner that would otherwise have been a restaurant reservation. The plate does not change with the occasion: salad, hibachi vegetables, fried rice, and two proteins. Chicken, steak, shrimp, salmon, and tofu are in the $50 price. Scallops and filet are +$5. Lobster tail is +$15."] },
        { h2: "Headcount and the day", p: ["Children 12 and under are $25. Every party has a $500 minimum. At 30 adults, book two chefs. Gratuity is not included, and 20% is the suggestion. The price can change with the address, which matters when the party is in Bee Cave or Lakeway rather than central Austin. Payment is cash on the day. There is no deposit."] },
        { h2: "How to reserve Austin", p: ["Use the Austin page to hold the date, then watch email for the confirmation. Support usually writes about six days before the party. If the headcount or the protein list changes, call or text (929) 992-9932. Tell us then about allergies. The food has no nuts or sesame, gluten-free soy and teriyaki can be packed, and tofu is the vegetarian plate at the same per-person price."] },
      ],
    }),
    cityPost({
      id: "dallas",
      name: "Dallas",
      abbr: "TX",
      landing: "dallas-hibachi-at-home",
      booking: "dallas-tx",
      image: IMG[1],
      kicker: "Dallas",
      description: "Outdoor hibachi in Dallas, Plano, Frisco, Highland Park, and Preston Hollow. Private chef, grill, and show. $50 per person, $500 minimum.",
      dek: "Uptown terraces, north-Dallas yards, and larger parties in Plano and Frisco.",
      related: ["outdoor-hibachi-across-texas", "outdoor-hibachi-in-fort-worth", "outdoor-hibachi-in-austin", "outdoor-hibachi-party"],
      links: [
        { href: "/blog/outdoor-hibachi-across-texas/", label: "Texas overview" },
        { href: "/blog/outdoor-hibachi-in-fort-worth/", label: "Fort Worth" },
        { href: "/blog/outdoor-hibachi-in-austin/", label: "Austin" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Dallas splits into two kinds of address. Uptown is often a terrace. Highland Park and Preston Hollow are backyard dinners. Plano, Frisco, Richardson, Allen, and Las Colinas are where the headcount tends to grow, and that is the detail to send when you book, because the chef count follows the number of adults."] },
        { h2: "Terrace or a full yard", p: ["A terrace still works. The grill stays outdoors, and guests can sit inside if the seating is there. A Preston Hollow or Frisco yard gives the show more room, which is nicer when the guest list is long, but it is not a requirement. You provide the tables, chairs, plates, and utensils either way."] },
        { h2: "When the party needs two chefs", p: ["Thirty or more adults means two chefs, so the plates and the show stay on time. That comes up often on Plano and Frisco dates. The base price is still $50 per adult and $25 per child 12 and under, with a $500 minimum. Gratuity is separate. Suggested gratuity is 20%. The final price can vary by the exact address, including a drive north to Allen or Frisco."] },
        { h2: "What to send with the date", p: ["Address, headcount, two proteins per guest, and any allergy. Chicken, steak, shrimp, salmon, and tofu are included. Scallops and filet mignon are +$5, lobster tail is +$15, and noodles are +$4. There are no nuts or sesame. Gluten-free soy and teriyaki are available if you ask before the day. Tofu replaces meat at the same price."] },
        { h2: "Booking Dallas", p: ["Reserve from the Dallas page. After the calendar hold, check email for confirmation. The team usually contacts you about six days out. Cash is due the day of the party, with no deposit. Text (929) 992-9932 if the list changes after you book."] },
      ],
    }),
    cityPost({
      id: "fort-worth",
      name: "Fort Worth",
      abbr: "TX",
      landing: "fort-worth-hibachi-at-home",
      booking: "fort-worth-tx",
      image: IMG[2],
      kicker: "Fort Worth",
      description: "Outdoor hibachi in Fort Worth, Southlake, Keller, and the Cultural District. A private chef cooks at the house. $50 per person.",
      dek: "In-town yards around TCU and the Cultural District, plus Southlake and Keller.",
      related: ["outdoor-hibachi-across-texas", "outdoor-hibachi-in-dallas", "outdoor-hibachi-in-austin", "outdoor-hibachi-setup"],
      links: [
        { href: "/blog/outdoor-hibachi-across-texas/", label: "Texas overview" },
        { href: "/blog/outdoor-hibachi-in-dallas/", label: "Dallas" },
        { href: "/blog/outdoor-hibachi-in-houston/", label: "Houston" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Fort Worth uses the same chef, grill, and plate as Dallas and Austin, but the drive is the west side of the metro. Cultural District and TCU parties are in town. Southlake, Keller, Alliance, and Westover Hills are a different trip, so the street address decides timing and whether a location adjustment applies."] },
        { h2: "The outdoor spot", p: ["Backyard, patio, balcony, terrace, or under an awning. The grill does not come inside. If the group would rather eat in the house, set that table too. The show stays at the grill. Setup is usually a few minutes once the chef is on site. You still put out tables, chairs, plates, and utensils."] },
        { h2: "Weekends and birthdays", p: ["Fort Worth dates are often a birthday or a weekend dinner for family around those neighborhoods. The menu is per person: salad, hibachi vegetables, fried rice, and two proteins from chicken, steak, shrimp, salmon, and tofu. Upgrades are scallops or filet at +$5 and lobster tail at +$15. Edamame is $5 and gyoza is $10 if you want a plate before the grill starts."] },
        { h2: "Price on the Fort Worth side", p: ["$50 per person, $25 for a child 12 and under, $500 minimum. Gratuity is not in that number. Twenty percent is the suggestion. Parties of 30 or more adults are scheduled with two chefs. Payment is cash on the day, and there is no deposit. Because Southlake and Alliance are not the same drive as a TCU rental, mention the town when you ask about the date."] },
        { h2: "Reserve Fort Worth", p: ["Open the Fort Worth page and hold the date there. Confirmation comes by email, and support typically checks in about six days before. Allergies, gluten-free soy sauce, and a tofu plate should be on that note. Call or text (929) 992-9932 if the headcount moves."] },
      ],
    }),
    cityPost({
      id: "houston",
      name: "Houston",
      abbr: "TX",
      landing: "houston-hibachi-at-home",
      booking: "houston-tx",
      image: IMG[3],
      kicker: "Houston",
      description: "Outdoor hibachi in Houston, from River Oaks and the Heights to Katy, Sugar Land, and The Woodlands. $50 per person, $500 minimum.",
      dek: "Inside the city, or a drive out to Katy, Sugar Land, and The Woodlands.",
      related: ["outdoor-hibachi-across-texas", "outdoor-hibachi-in-austin", "outdoor-hibachi-in-dallas", "outdoor-hibachi-setup"],
      links: [
        { href: "/blog/outdoor-hibachi-across-texas/", label: "Texas overview" },
        { href: "/blog/outdoor-hibachi-in-austin/", label: "Austin" },
        { href: "/blog/outdoor-hibachi-in-dallas/", label: "Dallas" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Houston has to say which part of the city, because River Oaks, the Heights, Memorial, and Montrose are not the same booking as Katy, Sugar Land, or The Woodlands. The menu is the same. The address tells us whether the date is open and whether the price changes with the drive."] },
        { h2: "Cook outside, eat inside", p: ["Houston parties often keep the guests in the air conditioning and the grill on the patio. That fits the service: the chef cooks outdoors, on a backyard, balcony, terrace, or under an awning, and the plates can move inside. The host provides the furniture and the place settings. The chef brings the hibachi grill, the food, and the show."] },
        { h2: "The plate", p: ["Each guest gets two proteins, a salad, hibachi vegetables, and fried rice. Chicken, steak, shrimp, salmon, and tofu are in the base price of $50. A third protein is extra, noodles are +$4, and a side of fried rice is +$4. Vegetarian and vegan guests take tofu at the same per-person rate, with extra vegetables, salad, and rice as needed."] },
        { h2: "Suburbs and headcount", p: ["Katy, Sugar Land, and The Woodlands are served when the date is open, not as a standing promise for every Saturday. Send the street address with the request. Children 12 and under are $25, and the party minimum is $500. Thirty or more adults need two chefs. Gratuity is not included. Payment is cash that day, with no deposit."] },
        { h2: "Book the Houston date", p: ["Start on the Houston page. After you reserve, look for the confirmation email. About six days before, support confirms details. Mention allergies then. The kitchen does not use nuts or sesame, and gluten-free soy and teriyaki can be brought if you ask ahead. Questions go to (929) 992-9932."] },
      ],
    }),
    cityPost({
      id: "new-york",
      name: "New York",
      abbr: "NY",
      landing: "new-york-hibachi-at-home",
      booking: "new-york",
      image: IMG[4],
      kicker: "New York",
      description: "Outdoor hibachi in New York for homes, backyards, and terraces. The grill stays outside. $50 per person, $500 minimum.",
      dek: "Terraces and balconies more often than a lawn. The grill still stays outside.",
      related: ["outdoor-hibachi-across-new-york", "outdoor-hibachi-in-new-jersey", "outdoor-hibachi-setup", "outdoor-hibachi-vs-restaurant"],
      links: [
        { href: "/blog/outdoor-hibachi-across-new-york/", label: "New York overview" },
        { href: "/blog/outdoor-hibachi-in-new-jersey/", label: "New Jersey" },
        { href: "/blog/outdoor-hibachi-setup/", label: "Setup" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in New York is usually a terrace, a balcony, or a backyard behind a house, not a restaurant dining room. The chef arrives with the grill and the ingredients, sets up outside, and cooks there. Guests can eat outdoors with the show or at a table inside. Indoor dining is fine. Indoor cooking is not."] },
        { h2: "Tight outdoor space", p: ["Say so if the terrace is small, the awning is low, or the path to the grill is a narrow stair. Those details decide whether the spot is safe. They do not change the plate. A patio, a terrace, and a true backyard are all on the New York list when the chef can stand outside with the grill."] },
        { h2: "What the evening is", p: ["This is a private party at the home. You keep the guest list. The chef does the teppanyaki show and the dinner: salad, vegetables, fried rice, and two proteins. Chicken, steak, shrimp, salmon, and tofu are included at $50 per person. Children 12 and under are $25. The minimum is $500 even for a smaller terrace dinner."] },
        { h2: "Upgrades and the house rules", p: ["Scallops and filet mignon are +$5. Lobster tail is +$15. Noodles are +$4. You provide tables, chairs, plates, and utensils, which matters in a New York apartment where the rental may not have a full set for every guest. No nuts or sesame. Gluten-free sauces if you ask. Tofu for vegetarian guests at the same price. Gratuity is extra, suggested at 20%. Cash on the day, no deposit."] },
        { h2: "The New York calendar", p: ["New York has its own booking calendar. Reserve there, then watch for the confirmation email. Support contacts you about six days before. If the headcount changes, call or text (929) 992-9932. Parties of 30 or more adults are booked with two chefs, which is a tight fit on a small terrace, so mention the outdoor space when the list is that large."] },
      ],
    }),
    cityPost({
      id: "new-jersey",
      name: "New Jersey",
      abbr: "NJ",
      landing: "new-jersey-hibachi-at-home",
      booking: "new-jersey",
      image: IMG[5],
      kicker: "New Jersey",
      description: "Outdoor hibachi in New Jersey for North Jersey and Central Jersey backyard parties. Town confirmed from your address. $50 per person.",
      dek: "North Jersey and Central Jersey backyards. The town is confirmed from the address.",
      related: ["outdoor-hibachi-across-new-jersey", "outdoor-hibachi-in-new-york", "outdoor-hibachi-in-pennsylvania", "outdoor-hibachi-party"],
      links: [
        { href: "/blog/outdoor-hibachi-across-new-jersey/", label: "New Jersey overview" },
        { href: "/blog/outdoor-hibachi-in-new-york/", label: "New York" },
        { href: "/blog/outdoor-hibachi-in-pennsylvania/", label: "Pennsylvania" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in New Jersey is a backyard party. Hibachi King cooks for North Jersey and Central Jersey when the town checks out from the street address. It is not a statewide route, and it is not a restaurant reservation. The chef brings a grill, salad, vegetables, fried rice, and two protein choices per guest."] },
        { h2: "Why the town matters", p: ["Two New Jersey parties on the same Saturday can be a very different drive. We confirm the town before the event so the date and any location adjustment are real. Put the full address in the booking. A backyard is the usual setup. A patio or a spot under an awning also works. The grill stays outside."] },
        { h2: "What you set out", p: ["Tables, chairs, plates, and utensils stay with the house. The chef does not bring a dining room. If some guests will eat inside, set that table as well. The show can remain in the yard. Licensed and insured, same as the other cities."] },
        { h2: "Price", p: ["$50 per person, $25 for children 12 and under, $500 minimum. Suggested gratuity is 20% and is not included. At 30 adults, schedule two chefs. Cash only, paid the day of the party, with no deposit. The price may vary by location once the town is confirmed."] },
        { h2: "Book New Jersey", p: ["New Jersey has its own calendar. Hold the date there, then check email. About six days out, support goes over headcount and allergies. No nuts or sesame in the food. Gluten-free soy and teriyaki on request. Tofu at the regular per-person price for vegetarian and vegan guests. The phone is (929) 992-9932."] },
      ],
    }),
    cityPost({
      id: "pennsylvania",
      name: "Pennsylvania",
      abbr: "PA",
      landing: "pennsylvania-hibachi-at-home",
      booking: "pennsylvania",
      image: IMG[0],
      kicker: "Pennsylvania",
      description: "Outdoor hibachi in Pennsylvania for Philadelphia-area parties at home. Availability comes from the street address. $50 per person.",
      dek: "Philadelphia and nearby suburbs. The street address decides the date.",
      related: ["outdoor-hibachi-across-pennsylvania", "outdoor-hibachi-in-new-jersey", "outdoor-hibachi-in-new-york", "outdoor-hibachi-cost"],
      links: [
        { href: "/blog/outdoor-hibachi-across-pennsylvania/", label: "Pennsylvania overview" },
        { href: "/blog/outdoor-hibachi-in-new-jersey/", label: "New Jersey" },
        { href: "/blog/outdoor-hibachi-in-new-york/", label: "New York" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Pennsylvania is centered on Philadelphia and nearby suburbs, not on every town in the state. A city yard and a suburban backyard are both possible. Which one can be served on your date depends on the street address, so that address is the first thing to send, along with the headcount."] },
        { h2: "City yard or suburban lawn", p: ["A Philadelphia house may have a small yard, a patio, or only a spot under cover. A suburban party usually has more room for the grill and the guests. Both are outdoor cooking. The chef does not move the grill indoors. Guests can still eat inside if that is how the house is set. You provide tables, chairs, plates, and utensils."] },
        { h2: "The menu stays plain", p: ["Two proteins from chicken, steak, shrimp, salmon, and tofu. Salad, hibachi vegetables, and fried rice on the plate. Scallops and filet mignon are +$5. Lobster tail is +$15. Noodles are +$4. The base rate is $50 per person and $25 for a child 12 and under, with a $500 minimum. Gratuity is extra."] },
        { h2: "Tell the kitchen before the day", p: ["The food does not contain nuts or sesame. Other allergies need a note when you book. Gluten-free soy and teriyaki can be packed. Tofu is available at the same price. If the party is 30 adults or more, two chefs are required. Payment is cash on the day. There is no deposit. Location can change the price, which is another reason the Philadelphia address has to be specific."] },
        { h2: "Reserve Pennsylvania", p: ["Book from the Pennsylvania page and include where the party will be. Confirmation is by email. Support usually reaches out about six days ahead. Call or text (929) 992-9932 if the suburb or the guest count changes after that."] },
      ],
    }),
    cityPost({
      id: "miami",
      name: "Miami",
      abbr: "FL",
      landing: "miami-hibachi-at-home",
      booking: "miami-fl",
      image: IMG[1],
      kicker: "Miami",
      description: "Outdoor hibachi in Miami for Brickell, Coral Gables, Miami Beach, Doral, Aventura, and Kendall. Patio and vacation-rental parties. $50 per person.",
      dek: "Brickell terraces, Coral Gables yards, Miami Beach, and a safe spot by the pool.",
      related: ["outdoor-hibachi-across-florida", "outdoor-hibachi-in-orlando", "outdoor-hibachi-party", "outdoor-hibachi-setup"],
      links: [
        { href: "/blog/outdoor-hibachi-across-florida/", label: "Florida overview" },
        { href: "/blog/outdoor-hibachi-in-orlando/", label: "Orlando" },
        { href: "/blog/outdoor-hibachi-setup/", label: "Setup" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Miami is booked by neighborhood, because a Brickell terrace, a Coral Gables house, and a Miami Beach rental are different setups. Doral, Aventura, and Kendall are on the list when the date is open. The show works on a patio, or beside a pool, only when the chef has a safe outdoor place for the grill."] },
        { h2: "High-rise, house, or rental", p: ["A tower terrace needs enough floor for the grill and a clear way to bring it up. A house in Coral Gables or Kendall usually has a yard. A vacation rental needs the same thing every other party needs from the host: tables, chairs, plates, and utensils. The chef does not supply the dining room. The chef does bring the grill, the food, and the show, and cooks outside."] },
        { h2: "The Miami plate", p: ["Salad, hibachi vegetables, fried rice, and two proteins per person. Chicken, steak, shrimp, salmon, and tofu are included at $50. Children 12 and under are $25. The minimum is $500. Scallops and filet are +$5, lobster tail is +$15. Parties of 30 or more adults are scheduled with two chefs, which is worth deciding before you hold a large Miami Beach date."] },
        { h2: "Payment and allergies", p: ["Cash on the day of the event. No deposit. Gratuity is not included, and 20% is the suggestion. The price can vary by location. No nuts or sesame. Ask for gluten-free soy and teriyaki when you book. Tofu covers vegetarian and vegan guests at the regular rate."] },
        { h2: "Miami's calendar", p: ["Miami has its own appointment calendar. Reserve there, then watch email for confirmation. About six days before, support contacts you. If the rental address or the headcount changes, text (929) 992-9932. Do not assume a pool deck is approved until the outdoor spot is described."] },
      ],
    }),
    cityPost({
      id: "orlando",
      name: "Orlando",
      abbr: "FL",
      landing: "orlando-hibachi-at-home",
      booking: "orlando-fl",
      image: IMG[2],
      kicker: "Orlando",
      description: "Outdoor hibachi in Orlando for homes and vacation rentals in Dr. Phillips, Winter Park, Lake Nona, and Kissimmee. $50 per person.",
      dek: "Vacation rentals and reunion weekends, from Dr. Phillips to Kissimmee.",
      related: ["outdoor-hibachi-across-florida", "outdoor-hibachi-in-miami", "outdoor-hibachi-party", "outdoor-hibachi-birthday"],
      links: [
        { href: "/blog/outdoor-hibachi-across-florida/", label: "Florida overview" },
        { href: "/blog/outdoor-hibachi-in-miami/", label: "Miami" },
        { href: "/blog/outdoor-hibachi-birthday/", label: "Birthdays" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Orlando is often a vacation rental rather than the host's own house. Family reunions, birthday weekends, and trip celebrations book around Dr. Phillips, Winter Park, Lake Nona, and Kissimmee. The chef cooks at that address. The group skips a crowded restaurant and keeps the list private."] },
        { h2: "What a rental still has to have", p: ["The chef brings the grill and the food. The rental has to cover tables, chairs, plates, and utensils, same as a private home. If the house is short on place settings, that is the host's job before the chef arrives. The grill goes in the backyard, on a patio, or under an awning. It does not come indoors. Guests can eat inside."] },
        { h2: "Reunions and kids", p: ["A reunion weekend mixes adults and children. Adults are $50, children 12 and under are $25, and the $500 minimum applies to the whole party. Each person picks two proteins: chicken, steak, shrimp, salmon, or tofu. At 30 adults, plan on two chefs so a long table does not wait on one grill."] },
        { h2: "Allergies on a trip", p: ["Tell us when you book, not at the door. There are no nuts or sesame. Gluten-free soy and teriyaki can be packed for the party. Tofu is the vegetarian and vegan plate at the same per-person price, with extra vegetables, salad, and fried rice as needed. Gratuity is separate, suggested at 20%. Cash on the day. No deposit."] },
        { h2: "Book Orlando", p: ["Use the Orlando page and put the rental address in the notes if the form allows, or send it when support writes about six days before. Confirmation is email. The price can change with the location, so Kissimmee and Winter Park should not be treated as the same drive. Call or text (929) 992-9932 with changes."] },
      ],
    }),
    cityPost({
      id: "phoenix",
      name: "Phoenix",
      abbr: "AZ",
      landing: "phoenix-hibachi-at-home",
      booking: "phoenix-az",
      image: IMG[3],
      kicker: "Phoenix",
      description: "Outdoor hibachi in Phoenix for Arcadia, Biltmore, Tempe, Chandler, and Gilbert patios. Private chef at the house. $50 per person.",
      dek: "Patio dinners in Arcadia, Biltmore, Tempe, Chandler, and Gilbert.",
      related: ["outdoor-hibachi-across-arizona", "outdoor-hibachi-setup", "outdoor-hibachi-cost", "outdoor-hibachi-party"],
      links: [
        { href: "/blog/outdoor-hibachi-across-arizona/", label: "Arizona overview" },
        { href: "/blog/outdoor-hibachi-setup/", label: "Setup" },
        { href: "/blog/outdoor-hibachi-cost/", label: "Cost" },
      ],
      blocks: [
        { p: ["Outdoor hibachi in Phoenix is a patio party. The grill is set outside at houses in Arcadia, the Biltmore area, Tempe, Chandler, Gilbert, and other East Valley addresses we can confirm. Guests stay in the yard for the flames and the knife work, then eat the plated dinner there or at a table you have already set."] },
        { h2: "A patio that can hold the grill", p: ["The chef needs a safe outdoor spot: backyard, terrace, or under an awning. Covered patios are common and they work when the chef can cook outside rather than in a closed room. You provide tables, chairs, plates, and utensils. The visit includes the grill, the food, and the show. Setup is usually a few minutes after arrival."] },
        { h2: "East Valley versus central Phoenix", p: ["Arcadia and Biltmore are not the same drive as Chandler or Gilbert. Tempe sits between them. Send the actual address so the date and any location adjustment are based on that street, not on the word Phoenix. We do not treat every East Valley town as automatically on the route."] },
        { h2: "Price in the yard", p: ["$50 per adult and $25 per child 12 and under, with a $500 minimum. Gratuity is separate, suggested at 20%, and the price can change with location. Two proteins, salad, vegetables, and fried rice are the plate. Scallops and filet are +$5. Lobster tail is +$15. Thirty or more adults means two chefs. Cash on the day. No deposit."] },
        { h2: "Reserve Phoenix", p: ["Book from the Phoenix page. Email confirms the hold. About six days before, support checks the details. Mention allergies, gluten-free sauces, or tofu then. No nuts or sesame are used. Text (929) 992-9932 if you want the headcount checked before you book."] },
      ],
    }),
  ];

  const states = [
    statePost({
      slug: "texas",
      name: "Texas",
      image: IMG[0],
      kicker: "Texas",
      description: "Outdoor hibachi across Texas in Austin, Dallas, Fort Worth, and Houston, including nearby suburbs on each city's list. Same menu, local address.",
      dek: "Four cities, one menu. The address decides which page to book.",
      related: ["outdoor-hibachi-in-austin", "outdoor-hibachi-in-dallas", "outdoor-hibachi-in-fort-worth", "outdoor-hibachi-in-houston"],
      links: [
        { href: "/blog/outdoor-hibachi-in-austin/", label: "Austin" },
        { href: "/blog/outdoor-hibachi-in-dallas/", label: "Dallas" },
        { href: "/blog/outdoor-hibachi-in-fort-worth/", label: "Fort Worth" },
        { href: "/blog/outdoor-hibachi-in-houston/", label: "Houston" },
      ],
      blocks: [
        { p: ["Outdoor hibachi across Texas runs through four cities: Austin, Dallas, Fort Worth, and Houston. The plate is the same in each, at $50 per person, $25 for children 12 and under, and a $500 minimum. What changes is the drive, the kind of yard, and which booking page holds the date."] },
        { h2: "Pick the city that matches the house", p: ["Austin covers central neighborhoods plus Round Rock, Cedar Park, Westlake, Lakeway, and Bee Cave. Dallas covers Uptown, Highland Park, Preston Hollow, Plano, Frisco, Richardson, Las Colinas, and Allen. Fort Worth covers the Cultural District, TCU, Southlake, Keller, Alliance, and Westover Hills. Houston covers River Oaks, the Heights, Memorial, Montrose, Katy, Sugar Land, and The Woodlands when the date is open."] },
        { h2: "Book the city that has the house", p: ["A Frisco party belongs on the Dallas page. A Southlake party belongs on Fort Worth. A Woodlands party belongs on Houston. Using the nearest city name is how the address gets confirmed and how a location adjustment, if any, is quoted. Gratuity is not included. Cash is due the day of the party. Thirty or more adults need two chefs."] },
        { h2: "Read the city note", p: ["Each city has its own article for the local setup, then a landing page with the calendar. Start with the note if you are choosing between two Texas cities, then reserve on the page that names the town where the grill will actually be."] },
      ],
    }),
    statePost({
      slug: "florida",
      name: "Florida",
      image: IMG[1],
      kicker: "Florida",
      description: "Outdoor hibachi across Florida in Miami and Orlando, including vacation rentals. Neighborhoods and rental addresses are confirmed per city.",
      dek: "Miami neighborhoods and Orlando rental weekends. Two cities, not the whole state.",
      related: ["outdoor-hibachi-in-miami", "outdoor-hibachi-in-orlando", "outdoor-hibachi-party", "outdoor-hibachi-setup"],
      links: [
        { href: "/blog/outdoor-hibachi-in-miami/", label: "Miami" },
        { href: "/blog/outdoor-hibachi-in-orlando/", label: "Orlando" },
      ],
      blocks: [
        { p: ["Outdoor hibachi across Florida means Miami and Orlando. It does not mean every Florida city. Miami is a neighborhood booking: Brickell, Coral Gables, Miami Beach, Doral, Aventura, and Kendall, often a terrace or a patio with a safe spot for the grill. Orlando is often a vacation rental in Dr. Phillips, Winter Park, Lake Nona, or Kissimmee."] },
        { h2: "Why the parties feel different", p: ["A Miami date is frequently the host's house or a short-stay rental near the water, with the guest list already in town. An Orlando date is frequently a reunion or a birthday weekend where everyone is staying in one house. Both still need the host to set tables, chairs, plates, and utensils. The chef brings the grill and cooks outside."] },
        { h2: "Same price, separate calendars", p: ["$50 per person, $25 for kids 12 and under, $500 minimum, gratuity extra. Miami has its own appointment calendar. Orlando is booked from the Orlando page. Do not use one city's hold for the other city's address. The price can change with location. Cash on the day, no deposit, and two chefs at 30 adults."] },
        { h2: "Which note to read", p: ["Read the Miami note if the party is a patio, a tower terrace, or a pool deck that still needs a safety check. Read the Orlando note if the address is a rental and you need to plan place settings before the chef arrives."] },
      ],
    }),
    statePost({
      slug: "new-york",
      name: "New York",
      image: IMG[4],
      kicker: "New York",
      description: "Outdoor hibachi across New York is the New York City home service: terrace, balcony, or backyard. The grill stays outside. $50 per person.",
      dek: "One service city. Terrace and balcony cooking, with a link to the New York note.",
      related: ["outdoor-hibachi-in-new-york", "outdoor-hibachi-in-new-jersey", "outdoor-hibachi-setup", "outdoor-hibachi-vs-restaurant"],
      links: [
        { href: "/blog/outdoor-hibachi-in-new-york/", label: "New York city note" },
        { href: "/blog/outdoor-hibachi-in-new-jersey/", label: "New Jersey" },
      ],
      blocks: [
        { p: ["Outdoor hibachi across New York, for Hibachi King, is the New York home service. It is not a tour of upstate cities. The parties are private homes, backyards, terraces, and patios. The chef cooks outside and brings the grill, the food, and the show."] },
        { h2: "What makes this market different", p: ["Many addresses do not have a lawn. The workable spot is a terrace, a balcony, or a backyard behind a house, sometimes under an awning. Tell us about limited floor space when you book. Guests may eat inside. The grill may not. You still provide tables, chairs, plates, and utensils."] },
        { h2: "Price and the calendar", p: ["$50 per person, $25 for children 12 and under, $500 minimum. Gratuity is not included. New York has its own booking calendar, separate from New Jersey. A New Jersey backyard should be booked on the New Jersey page even when the host lives in New York during the week. Cash on the day. No deposit. Two chefs when the adult count reaches 30, and the terrace has to be able to hold that."] },
        { h2: "Read next", p: ["The New York city note goes into terrace setup, upgrades, and how confirmation works. Use that, then reserve on the New York page."] },
      ],
    }),
    statePost({
      slug: "new-jersey",
      name: "New Jersey",
      image: IMG[5],
      kicker: "New Jersey",
      description: "Outdoor hibachi across New Jersey for North Jersey and Central Jersey backyards. The town is confirmed from the party address.",
      dek: "North Jersey and Central Jersey only, confirmed town by town.",
      related: ["outdoor-hibachi-in-new-jersey", "outdoor-hibachi-in-new-york", "outdoor-hibachi-in-pennsylvania", "outdoor-hibachi-party"],
      links: [
        { href: "/blog/outdoor-hibachi-in-new-jersey/", label: "New Jersey note" },
        { href: "/blog/outdoor-hibachi-in-new-york/", label: "New York" },
        { href: "/blog/outdoor-hibachi-in-pennsylvania/", label: "Pennsylvania" },
      ],
      blocks: [
        { p: ["Outdoor hibachi across New Jersey covers North Jersey and Central Jersey backyard parties. The town is confirmed from the event address before the date is treated as final. South Jersey is not listed as a service area. If the house is in Pennsylvania or New York, use that city's page instead."] },
        { h2: "Backyards, not a statewide tour", p: ["The usual party is a house with a yard. A patio or a covered spot still works when the chef can cook outside. The host sets the table. Hibachi King sends the chef, the grill, the food, and the show. Because two towns in the same half of the state can be a long drive apart, the street address is required."] },
        { h2: "Shared rules", p: ["$50 per person, $25 for a child 12 and under, $500 minimum, gratuity extra at a suggested 20%. Cash on the day, no deposit. Two chefs at 30 adults. No nuts or sesame. New Jersey has its own calendar, separate from the New York calendar."] },
        { h2: "Where to go next", p: ["The New Jersey note explains the backyard setup and what to send with the booking. Reserve on the New Jersey page after the town is one we can confirm."] },
      ],
    }),
    statePost({
      slug: "pennsylvania",
      name: "Pennsylvania",
      image: IMG[0],
      kicker: "Pennsylvania",
      description: "Outdoor hibachi across Pennsylvania is a Philadelphia-area service. Nearby suburbs are confirmed from the party address. $50 per person.",
      dek: "Philadelphia and nearby suburbs. Not a promise for the whole state.",
      related: ["outdoor-hibachi-in-pennsylvania", "outdoor-hibachi-in-new-jersey", "outdoor-hibachi-in-new-york", "outdoor-hibachi-cost"],
      links: [
        { href: "/blog/outdoor-hibachi-in-pennsylvania/", label: "Pennsylvania note" },
        { href: "/blog/outdoor-hibachi-in-new-jersey/", label: "New Jersey" },
      ],
      blocks: [
        { p: ["Outdoor hibachi across Pennsylvania is a Philadelphia-area service, plus nearby suburbs when the address can be confirmed. It is not a standing route to every Pennsylvania city. Availability and any location adjustment come from the street where the party will be."] },
        { h2: "What the local parties look like", p: ["Some are smaller city yards. Some are suburban lawns with room for the grill and a long table. In both cases the chef cooks outdoors and the host provides tables, chairs, plates, and utensils. The menu is the standard plate: two proteins, salad, vegetables, and fried rice, at $50 per person with a $500 minimum."] },
        { h2: "Book with the address", p: ["Use the Pennsylvania page and include the town. A New Jersey address should not be forced onto this calendar. Confirmation is email, with a check-in about six days before. Cash on the day, no deposit, gratuity not included."] },
        { h2: "Read the city note", p: ["The Pennsylvania article covers the difference between a Philadelphia yard and a suburban one, plus allergies and upgrades. Start there if you are not sure the suburb is close enough."] },
      ],
    }),
    statePost({
      slug: "arizona",
      name: "Arizona",
      image: IMG[3],
      kicker: "Arizona",
      description: "Outdoor hibachi across Arizona is the Phoenix patio service, including Tempe, Chandler, Gilbert, and other East Valley addresses we confirm.",
      dek: "Phoenix patios and the East Valley. One metro, not the whole state.",
      related: ["outdoor-hibachi-in-phoenix", "outdoor-hibachi-setup", "outdoor-hibachi-cost", "outdoor-hibachi-party"],
      links: [
        { href: "/blog/outdoor-hibachi-in-phoenix/", label: "Phoenix note" },
        { href: "/blog/outdoor-hibachi-setup/", label: "Setup" },
      ],
      blocks: [
        { p: ["Outdoor hibachi across Arizona is centered on Phoenix patios and nearby East Valley parties. Arcadia, the Biltmore area, Tempe, Chandler, and Gilbert are the places named on the Phoenix page. Other Arizona cities are not a separate service. An address still has to be confirmed before it is treated as on the route."] },
        { h2: "Why it is a patio service", p: ["The party is built for the yard. The chef sets the grill outside. Guests watch the show there. A covered patio works when the cooking itself stays outdoors. The host provides the table setting. This is the same rule as every other city, and it matters on patios that were not planned as a dining room."] },
        { h2: "Price", p: ["$50 per adult, $25 per child 12 and under, $500 minimum. Gratuity suggested at 20% and not included. The price can change with location, so a Gilbert address is not automatically the Arcadia price. Cash on the day. No deposit. Two chefs at 30 adults."] },
        { h2: "Next step", p: ["Read the Phoenix note for the neighborhood list and how to describe the patio. Then book on the Phoenix page with the real street address."] },
      ],
    }),
  ];

  return [...cities, ...states];
}
